name: Build Library
run-name: Build Library
on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - uses: actions/checkout@v4
      name: Checking out project
      with:
          fetch-depth: 1
          repository: uprightech/cedarling-java-bridge
      
    - uses: actions/checkout@v4
      name: Checking out Janssen
      with:
        fetch-depth: 1
        repository: JanssenProject/jans
        path: jans
    
    - run: |
          mkdir -p $GITHUB_WORKSPACE/cedarling-java-bridge/crates/
          cp -r $GITHUB_WORKSPACE/jans/jans-cedarling/ $GITHUB_WORKSPACE/cedarling-java-bridge/crates/jans-cedarling
    
    - run: cargo build
      working-directory: ./cedarling-java-bridge