name: Build Library
run-name: Build Library
on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - run: echo $GITHUB_WORKSPACE

    - uses: actions/checkout@v4
      name: Checking out project
      with:
          fetch-depth: 1
          repository: uprightech/cedarling-java-bridge
      
    - uses: actions/checkout@v4
      name: Checking out Janssen
      with:
        fetch-depth: 1
        repository: JanssenProject/jans
        path: jans

    
    - run: cp -r $GITHUB_WORKSPACE/jans/jans-cedarling/ $GITHUB_WORKSPACE/cedarling-java-bridge/crates/jans-cedarling